### ISSUE TITLE
install_gpu_driver.py doesn't work for K80

### ISSUE THREAD

**Issue by sigmaxipi** [GoogleCloudPlatform/compute-gpu-installation#2]
I was able to use the script for P100 and V100 GCE instances but not K80.

Repro:
1. Create a k80 instance with `gcloud compute instances create n8-k80 --project=YOUR_PROJECT_NAME --zone=us-west1-b --machine-type=n1-highcpu-8 --network-interface=network=core-network,network-tier=PREMIUM --no-restart-on-failure --maintenance-policy=TERMINATE --preemptible --accelerator=count=1,type=nvidia-tesla-k80 --create-disk=auto-delete=yes,boot=yes,device-name=n8-v100,image=projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20210927,mode=rw,size=20`
2. SSH in
3. Run script with `wget https://raw.githubusercontent.com/GoogleCloudPlatform/compute-gpu-installation/main/linux/install_gpu_driver.py` and `sudo python3 install_gpu_driver.py`

Error:
Running `nvidia-smi` gives `NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.` even though the install script finished properly.

**Comment by jimmyorourke** [comment]
This is likely because the K80 is an older GPU and only compatible with drivers up to version 470 (based on what's available here https://www.nvidia.com/Download/Find.aspx).
The install_gpu_driver script uses package managers that are likely pulling the latest driver which is probably too new.

**Comment by m-strzelczyk** [comment]
@sigmaxipi Hi, thank you for the detailed reproduction steps!

The script will now support K80 GPUs and will install an older, but compatible version of the drivers for you :)
