### ISSUE TITLE
On Windows 2016, script must explicitly select TLS 1.2

### ISSUE THREAD

**Issue by tpdownes** [GoogleCloudPlatform/compute-gpu-installation#21]
**Describe the bug**
The [cloud.google.com instructions](https://cloud.google.com/compute/docs/gpus/install-drivers-gpu#installation_scripts) advise a two-step process for downloading and executing the script contained in this repo. I find that, on Windows 2016, the 1st step to download the script fails unless one previously sets TLS1.2:

```ps1
[Net.ServicePointManager]::SecurityProtocol = 'Tls12'
```

**Environment**
 - Operating system: What OS are you running, would be best to point at specific disk image on GCP you are using if it's public.

Windows 2016 family (latest)

 - Graphics card: What kind of GPU are you trying to use. How many devices do you have attached?

n1-standard-8 with 1 T4

**Comment by m-strzelczyk** [comment]
@tpdownes So the right way to download the script onto the machine is:

```
[Net.ServicePointManager]::SecurityProtocol = 'Tls12'
Invoke-WebRequest https://github.com/GoogleCloudPlatform/compute-gpu-installation/raw/main/windows/install_gpu_driver.ps1 -OutFile C:\install_gpu_driver.ps1
```

Right?

Windows 2016 seems to be out of it's [mainstream support](https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2016). But it's a small change, so we might suggest to add it to the documentation page and our README.

**Comment by tpdownes** [comment]
For clarity, I _believe_ that if one adds a 3rd line to run the script, then it inherits the TLS 1.2 setting. If it does not, I will say so explicitly here.

```ps1
[Net.ServicePointManager]::SecurityProtocol = 'Tls12'
Invoke-WebRequest https://github.com/GoogleCloudPlatform/compute-gpu-installation/raw/main/windows/install_gpu_driver.ps1 -OutFile C:\install_gpu_driver.ps1
C:\install_gpu_driver.ps1
```

**Comment by m-strzelczyk** [comment]
I have submitted a CL to the Cloud Docs. Inside the script #23 is taking care of setting TLS config for Windows 2016.

Waiting for the Docs page to update and will close this then :)
