### ISSUE TITLE
Windows script prompts for input

### ISSUE THREAD

**Issue by tpdownes** [GoogleCloudPlatform/compute-gpu-installation#22]
**Describe the bug**
The [instructions] for using this script clearly state "no command prompts are given during the installation process." When I invoke commands 1+2 (at link) through WinRM, however, it is clear that the script [stops for a prompt](https://github.com/GoogleCloudPlatform/compute-gpu-installation/blob/main/windows/install_gpu_driver.ps1#L57) with the message:

> Press any key to continue

[instructions]: https://cloud.google.com/compute/docs/gpus/install-drivers-gpu#windows

What am I missing? I believe that I'm running as Administrator, but is this prompt ignored under some conditions?

**Environment**
 - Operating system: What OS are you running, would be best to point at specific disk image on GCP you are using if it's public.

windows-2016 image family (latest)

 - Graphics card: What kind of GPU are you trying to use. How many devices do you have attached?

n1-standard-8 with 1 Tesla T4 attached

**To Reproduce**
Steps to reproduce the behavior. A copy-paste of the commands you executed and the output you got. The Linux installation script by default saves its' output to `/opt/google/gpu-installer/` - please provide the files you find there.

I am supplying the script below to a [Powershell provisioner](https://developer.hashicorp.com/packer/docs/provisioners/powershell) (WinRM) in packer. It is configured with `elevated_user = "Administrator"`.

```ps1
Set-StrictMode -Version latest
$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = 'Tls12'
Invoke-WebRequest https://github.com/GoogleCloudPlatform/compute-gpu-installation/raw/main/windows/install_gpu_driver.ps1 -OutFile C:\install_gpu_driver.ps1
C:\install_gpu_driver.ps1
```

I'll admit to inexperience with Windows PowerShell scripting, but the script seems plainly designed to prompt for input.

**Comment by m-strzelczyk** [comment]
The script will halt and wait for input only when it doesn't detect the connected GPU, as we can see from the code:

```
# Check if the GPU exists with Windows Management Instrumentation, returning the device ID if it exists
function Find-GPU {
    $MgmtCommand = Get-Mgmt-Command
    try {
        $Command = "(${MgmtCommand} -query ""select DeviceID from Win32_PNPEntity Where (deviceid Like '%PCI\\VEN_10DE%') and (PNPClass = 'Display' or Name = '3D Video Controller')"" | Select-Object DeviceID -ExpandProperty DeviceID).substring(13,8)"
        $dev_id = Invoke-Expression -Command $Command
        return $dev_id
    }
    catch {
        Write-Output "There doesn't seem to be a GPU unit connected to your system. Do you want to continue?"
        Read-Host -Prompt 'Press any key to continue'
        return ""
    }
}
```

There is the line that's causing the prompt: `Read-Host -Prompt 'Press any key to continue'`.

So it seems that the script doesn't find the GPU in Windows Management Instrumentation.

Can you perhaps inspect what's the value of `$Command` in your system? 

Would it be possible for you to use a newer Windows version?

**Comment by tpdownes** [comment]
I see 3 different `Read-Host -Prompt` lines. When I run it manually, it is stopping at the one I linked to (see below). All it appears to be doing is telling me that it didn't find the driver.

https://github.com/GoogleCloudPlatform/compute-gpu-installation/blob/eaa907edf715e295dbb53d56783d65d91c91c8ee/windows/install_gpu_driver.ps1#L57

**Comment by m-strzelczyk** [comment]
You are right, I did point out to the wrong line. The Pull Request #23 should solve your problem.

Can you give it a try and let me know if that worked as intended?
