### ISSUE TITLE
Nvidia driver stops working after reboot

### ISSUE THREAD

**Issue by m-matthias** [GoogleCloudPlatform/compute-gpu-installation#25]
**Describe the bug**
Hi, sometimes after I restart our instance, the Nvidia driver doesnt work and nvidia-smi fails with:
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
I installed the driver using the script from this repo. I already found a way to manually fix the issue by running: sudo apt-get install linux-headers-$(uname -r)
After this, the Nvidia driver works again. But after a few days, the issue appeared again. Is there way to permanently fix this?

**Environment**
 - Operating system: Debian 11
 - Graphics card: 1 Tesla P100

**To Reproduce**
Not sure how to reproduce it, issue appears sporadicly

**Comment by m-strzelczyk** [comment]
Hi @m-matthias!

Can you please have a look at issue #10 and check if this perhaps happens because of kernel updates? 

I'm not sure why installing linux-headers automatically would fix things though... But if it's a solution that simple, we may want to update the installation script to do this on every system start.

**Comment by m-strzelczyk** [comment]
I think there were some problems with the headers in repositories recently, as we saw couple of our other tools have some issues related to headers in Debian and Ubuntu.

I have just approved and merged #26 - could you try using the new version and let me know if the issue still happens?

**Comment by m-strzelczyk** [comment]
Well, #26 got reverted, so not much for you to test, sorry.

When I have some time available I'll see if I can replicate this behavior you're seeing and then try to fix it. For now, one other solution is to stop automatic kernel updates after installation. Then sometimes update it manually + install headers.

**Comment by m-matthias** [comment]
Can I stop automatic kernel updates via Google Cloud console or is this something I have to configure in Debian?

**Comment by m-strzelczyk** [comment]
@m-matthias It's something you'll have to do in Debian. Console has very limited access to what's going on inside the VMs.

**Comment by m-strzelczyk** [comment]
There is a new version of the installation tool available in the releases page. Feel free to try this one and hopefully it'll solve your problems.
