### ISSUE TITLE
Check Driver not calling nvidia-smi.exe correctly

### ISSUE THREAD

**Issue by weidhaus** [GoogleCloudPlatform/compute-gpu-installation#30]
**Describe the bug**
There is a bug in the Check Driver function which is causing the script to fail. 

**Environment**
 - Operating system: Win 10
 - Graphics card: L4

**To Reproduce**
To reproduce, follow these steps on a fresh install of Win:

- Open a PowerShell terminal as an administrator, then complete the following steps:
- If you are using Windows Server 2016, set the Transport Layer Security (TLS) version to 1.2.
`[Net.ServicePointManager]::SecurityProtocol = 'Tls12'`
- Download the script.
`Invoke-WebRequest https://github.com/GoogleCloudPlatform/compute-gpu-installation/raw/main/windows/install_gpu_driver.ps1 -OutFile C:\install_gpu_driver.ps1`
- Run the script.
`C:\install_gpu_driver.ps1`

To resolve, add the following to line 50 in [compute-gpu-installation](https://github.com/GoogleCloudPlatform/compute-gpu-installation/tree/main)/[windows](https://github.com/GoogleCloudPlatform/compute-gpu-installation/tree/main/windows)/install_gpu_driver.ps1:

`&'.\nvidia-smi.exe'`

**Comment by m-strzelczyk** [comment]
I'm not really familiar with how Windows scripting works. @weidhaus can you explain what's the difference between `&'.\nvidia-smi.exe'` and `&'nvidia-smi.exe'`? I thought that the latter looks for `nvidia-smi.exe` amond installed things in the system, while `.\nvidia-smi.exe` will use only the exe it finds in the current working directory.

**Comment by weidhaus** [comment]
After some double checking this is the correct form. I will close this.
