### ISSUE TITLE
install_gpu_driver.py fails on Ubntu 22.04.2 LTS with kernel 6.5.0-1018-gcp 

### ISSUE THREAD

**Issue by hkelley** [GoogleCloudPlatform/compute-gpu-installation#34]
**Describe the bug**
install_gpu_driver.py fails on Ubntu 22.04.2 LTS with kernel 6.5.0-1018-gcp 

**Environment**
x86_64
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy

gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0

kernel 6.5.0-1018-gcp

**To Reproduce**
```
curl https://raw.githubusercontent.com/GoogleCloudPlatform/compute-gpu-installation/main/linux/install_gpu_driver.py --output install_gpu_driver.py
sudo python3 install_gpu_driver.py

```

**Error Messages**
```
make[3]: *** [scripts/Makefile.build:251: /tmp/selfgz18649/NVIDIA-Linux-x86_64-525.125.06/kernel/nvidia/i2c_nvswitch.o] Error 1
make[3]: Target '/tmp/selfgz18649/NVIDIA-Linux-x86_64-525.125.06/kernel/' not remade because of errors.
make[2]: *** [/usr/src/linux-headers-6.5.0-1018-gcp/Makefile:2039: /tmp/selfgz18649/NVIDIA-Linux-x86_64-525.125.06/kernel] Error 2
make[2]: Target 'modules' not remade because of errors.
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Target 'modules' not remade because of errors.
make[1]: Leaving directory '/usr/src/linux-headers-6.5.0-1018-gcp'
make: *** [Makefile:82: modules] Error 2
ERROR: The nvidia kernel module was not created.
ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details
```

**Comment by wen020** [comment]
Any progress on this issue, I encountered it too

**Comment by m-strzelczyk** [comment]
Please use the new installer tool. We now use the [releases page](https://github.com/GoogleCloudPlatform/compute-gpu-installation/releases) to manage versions.
