### ISSUE TITLE
Nvidia-driver install fails. restarting VMs leaves them without use of the driver

### ISSUE THREAD

**Issue by GeorgePearse** [GoogleCloudPlatform/compute-gpu-installation#36]
**Describe the bug**
I've been hitting far more nvidia-driver problems than usual, most of the times I restart a GPU VM, it restarts without the nvidia-driver working. 

![image](https://github.com/GoogleCloudPlatform/compute-gpu-installation/assets/47161914/e0912fb8-91ca-42e3-9e26-92ec8ebe56cc)

I think this might be responsible?

**Comment by m-strzelczyk** [comment]
Can you please share more about your OS? Is it one of the supported ones or some other?

The `apt.kubernetes.io` repository doesn't look like one of the default repositories for Debian or Ubuntu. I think you'll need to remove it from your repository list to get unstuck.

**Comment by m-strzelczyk** [comment]
Please see [this issue](https://github.com/kubernetes/release/issues/3485) from Kubernetes. There you can find instructions on how to fix this. Please let me know if that worked.

Right now I don't think it's an issue with the installation tool, but with your system configuration (using deprecated repository).
