### ISSUE TITLE
Wrong public key when accessing nvidia cuda repo

### ISSUE THREAD

**Issue by SaschaSchuenemann** [GoogleCloudPlatform/compute-gpu-installation#41]
**Describe the bug**
The startup script fails due to wrong public key:

W: GPG error: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease' is not signed.

**Environment**
 - Operating system: Debian 12
 - Graphics card: What kind of GPU are you trying to use. How many devices do you have attached?
 - Compute Engine Instance Type: g2-standard-4

**To Reproduce**
Simply running the startup script within my compute engine VM throws this error.

**Comment by m-strzelczyk** [comment]
Can you share more info about the system you're running? I just tried the default Debian 12 on GCP and it worked fine. 

And to be sure, are you using the PYZ installer or the previous `[install_gpu_driver.py](https://github.com/GoogleCloudPlatform/compute-gpu-installation/blob/main/linux/install_gpu_driver.py)` one?

**Comment by m-strzelczyk** [comment]
Closing due to lack of reply.
