### ISSUE TITLE
Add CUDA installation to the Linux script

### ISSUE THREAD

**Issue by m-strzelczyk** [GoogleCloudPlatform/compute-gpu-installation#6]
We need to be able to install CUDA with the Linux script. This was lost when #4 got fixed, but would be great to have again.

**Comment by jimmyorourke** [comment]
This should be fixable by installing the CUDA toolkit, not just the driver, ie https://developer.nvidia.com/cuda-11-4-4-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=runfile_local.

I had mentioned this to Spencer but I guess it didn't get passed along.

**Comment by m-strzelczyk** [comment]
This is now done :D https://github.com/GoogleCloudPlatform/compute-gpu-installation/releases/tag/cuda-installer-v1.0.0
