### ISSUE TITLE
Installation failed on accelerator instance

### ISSUE THREAD

**Issue by yoanisgil** [GoogleCloudPlatform/compute-gpu-installation#8]
The installation script is throwing the following error when executed on an instance with a `A100 GPU`. The error is:
```
Failed with exception: list index out of range
Traceback (most recent call last):
  File "install_gpu_driver.py", line 375, in <module>
    raise err
  File "install_gpu_driver.py", line 372, in <module>
    main()
  File "install_gpu_driver.py", line 367, in main
    install(args)
  File "install_gpu_driver.py", line 346, in install
    if not detect_gpu_device() and not args.force:
  File "install_gpu_driver.py", line 143, in detect_gpu_device
    return re.findall("\[([\w\d\s]+)]", line)[0]
IndexError: list index out of range
```

Upon further inspection, the output from `lspci` shows:
```
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371AB/EB/MB PIIX4 ISA (rev 03)
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03)
00:03.0 Non-VGA unclassified device: Red Hat, Inc Virtio SCSI
00:04.0 3D controller: NVIDIA Corporation Device 20b0 (rev a1)
00:05.0 3D controller: NVIDIA Corporation Device 20b0 (rev a1)
00:06.0 3D controller: NVIDIA Corporation Device 20b0 (rev a1)
00:07.0 3D controller: NVIDIA Corporation Device 20b0 (rev a1)
00:08.0 Ethernet controller: Red Hat, Inc Virtio network device
00:09.0 Unclassified device [00ff]: Red Hat, Inc Virtio RNG
```

which does not match the expected pattern [here](https://github.com/GoogleCloudPlatform/compute-gpu-installation/blob/main/linux/install_gpu_driver.py#L142). I believe we should check if we were able to match the GPU name and if we do not then just return an empty string. This should fall in line with current logic, as it seems the script wants to verify the presence of a `NVIDIA K80` so that it uses a different installation script (otherwise the installation procedure does not rely on the GPU detected)

**Comment by timeemit** [comment]
+1 with a single attached T4 on Ubuntu 18.04

**Comment by JulesBelveze** [comment]
+1 with a double A100 on Ubuntu 20.04

**Comment by mkumar097** [comment]
+1, I am getting the same error.

**Comment by m-strzelczyk** [comment]
Thank you all for the reports, I'll be taking a look at this today.

**Comment by m-strzelczyk** [comment]
I have checked on systems with both K80 and A100 devices and the script works fine now. Sorry for the delay in resolving this.
